/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GameUI_utils_JNIUtils */

#ifndef _Included_GameUI_utils_JNIUtils
#define _Included_GameUI_utils_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GameUI_utils_JNIUtils
 * Method:    initializeGrid
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GameUI_utils_JNIUtils_initializeGrid
  (JNIEnv *, jclass);

/*
 * Class:     GameUI_utils_JNIUtils
 * Method:    getGridState
 * Signature: ([[C)V
 */
JNIEXPORT void JNICALL Java_GameUI_utils_JNIUtils_getGridState
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     GameUI_utils_JNIUtils
 * Method:    movePlayer
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_GameUI_utils_JNIUtils_movePlayer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     GameUI_utils_JNIUtils
 * Method:    moveEnemy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GameUI_utils_JNIUtils_moveEnemy
  (JNIEnv *, jclass);

/*
 * Class:     GameUI_utils_JNIUtils
 * Method:    isPlayerCaught
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_GameUI_utils_JNIUtils_isPlayerCaught
  (JNIEnv *, jclass);

/*
 * Class:     GameUI_utils_JNIUtils
 * Method:    isupgradable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_GameUI_utils_JNIUtils_isupgradable
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
